[book]
title = "Cargo 手册 中文版"
description = "Cargo 手册是使用 Cargo 全面指南教程，Cargo 是 Rust 的包管理器，通过本手册全面了解如何构建 Rust 程序和大型项目。"
author = "Alex Crichton, Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"

[output.html]
additional-js = ["language.js"]
git-repository-url = "https://github.com/rust-lang-cn/cargo-cn"
edit-url-template = "https://github.com/rust-lang-cn/cargo-cn/edit/master/{path}"
